services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -8000:8000

  mongoDb:
    ports:
      - 27017:27017
    volumes:
      - mongovolume:containerPath:ro

  volumes:
   - mongovolume

  