# Generated by Django 5.1.3 on 2024-11-20 12:20

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('506c7c30-b90a-45c6-a5d4-40118c241e41'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('506c7c30-b90a-45c6-a5d4-40118c241e41'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tractor_name', models.CharField(max_length=250)),
                ('model', models.CharField(choices=[('John Deere', 'Deere'), ('Mercy Ferguson', 'Ferguson')], default='John Deere', max_length=30)),
                ('year_of_manufucture', models.CharField(max_length=10)),
                ('engine_capacity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu')], default='Nairobi', max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Second Hand', 'Old')], default='Old', max_length=30)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='Petrol', max_length=30)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Manual', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('tractor_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractors', to='sellers.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TractorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_filename', models.CharField(max_length=255)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sellers.tractor')),
            ],
        ),
    ]
