# Generated by Django 5.1.3 on 2024-11-21 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f417ba38-ad3e-4670-a41f-1707cc1758b8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f417ba38-ad3e-4670-a41f-1707cc1758b8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
