# Generated by Django 5.1.3 on 2024-11-21 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_uid_alter_tractor_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6a6f65e7-0960-4a96-909c-df9e91d48463'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6a6f65e7-0960-4a96-909c-df9e91d48463'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_filename', models.CharField(max_length=255)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logoImages', to='sellers.seller')),
            ],
        ),
    ]
