# Generated by Django 5.1.3 on 2024-11-22 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_seller_seller_description_alter_seller_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4cfd4a89-dfb2-4873-b16d-45e9d3f099e2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4cfd4a89-dfb2-4873-b16d-45e9d3f099e2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
