# Generated by Django 5.1.3 on 2024-11-22 15:43

import datetime
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_seller_uid_alter_tractor_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('7e0f2e0d-b332-4048-ad2e-c5d1b37b09d5'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('7e0f2e0d-b332-4048-ad2e-c5d1b37b09d5'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('town', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tractor',
            name='Number_of_cylinders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tractor',
            name='Tractor_description',
            field=models.TextField(default=datetime.datetime(2024, 11, 22, 18, 43, 6, 16355)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tractor',
            name='Wheel_Drive',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tractor',
            name='forward_speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tractor',
            name='horse_power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tractor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='lifting_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tractor',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tractor',
            name='reverse_speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='seller',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7e0f2e0d-b332-4048-ad2e-c5d1b37b09d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='condition',
            field=models.CharField(choices=[('New Tractors', 'New Tractors'), ('Used Tractors', 'Used Tractors')], default='Old', max_length=30),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa')], default='Nairobi', max_length=20),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='model',
            field=models.CharField(choices=[('John Deere', 'John Deere'), ('Mercy Ferguson', 'John Deere')], default='John Deere', max_length=30),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Electric', 'Electric')], default='Manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7e0f2e0d-b332-4048-ad2e-c5d1b37b09d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
