# Generated by Django 5.1.3 on 2024-11-25 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_dealers_locations_tractor_number_of_cylinders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d6f7c9a-48c4-4934-ba6d-af671a707e05'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d6f7c9a-48c4-4934-ba6d-af671a707e05'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d6f7c9a-48c4-4934-ba6d-af671a707e05'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d6f7c9a-48c4-4934-ba6d-af671a707e05'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
