# Generated by Django 5.1.3 on 2024-11-25 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b7724c2d-6871-4e2b-9193-bbe6cf1f1ed6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
